### ISSUE TITLE
Make ReCaptchaV3 the default widget for ReCaptcha in the patches

### ISSUE THREAD

**Issue by fspc** [pbiering/mailman3-rpm#2]
Thank-you for providing the captcha patches.

reCAPTCHA v3 is  a nice alternative to v2, but the default behavior of your captcha patches is to provide a field for v2. 

With a simple code change in the patches, v3 could become the default behavior when CAPTCHA_SERVICE = 'recaptcha':

UNDER
`from django_recaptcha.fields import ReCaptchaField`
ADD
`from django_recaptcha.widgets import ReCaptchaV3`

For each instance of
```
if captcha_service == 'recaptcha':
        captcha = ReCaptchaField()
```
CHANGE TO
```
if captcha_service == 'recaptcha':
        captcha = ReCaptchaField(widget=ReCaptchaV3)
```

In the file django/contrib/admin/templates/admin/login.html
DO NOT SHOW this code when recaptcha is chosen as the service
```
  <div class="form-row">
    {{ form.captcha.errors }}
    {{ form.captcha }}
  </div>
```

Obviously, an alternative would be to provide two settings for recaptcha (recaptchaV2 and recaptchaV3).  If recaptchaV2 is chosen, then the form-row code would be shown, and the widget not used.

**Comment by pbiering** [comment]
Thank you for the hint, will investigate extension with V2Invisible and V3.

Regarding conditional template code for django/contrib/admin/templates/admin/login.html
Any clue how to toggle this by using config value CAPTCHA_SERVICE or at least honor a new variable set in the related Python code to hide for V2Invisible and V3?

**Comment by fspc** [comment]
> Regarding conditional template code for django/contrib/admin/templates/admin/login.html Any clue how to toggle this by using config value CAPTCHA_SERVICE or at least honor a new variable set in the related Python code to hide for V2Invisible and V3?

There is an extensive conversation at https://stackoverflow.com/questions/433162/can-i-access-constants-in-settings-py-from-templates-in-django , which presents many approaches.

For simplicity, the interesting solution that catches my attention is the django-settings-export app.

**Comment by pbiering** [comment]
@fspc : while working on implementation, can it be that https://pypi.org/project/django-recaptcha/ 4.0.0 broke "v2 checkbox" and "v2 invisible" support? I've tested with 3.0.0 last time, had not tested 4.0.0 with reCaptcha so far.

Found related javascript in HTML but not displayed in browser. v3 is working fine.

Keysets for all variants generated and selected.
No issue found with hCaptcha/FriendlyCaptcha/Turnstile

**Comment by fspc** [comment]
You are correct, with 4.0.0 the default "v2 checkbox" is not working, but v3 is working really well, and has completely stopped subscription spam.  I never tested "v2 checkbox".   We utilize the [dockerized version of mailman ]( https://github.com/maxking/docker-mailman ) where setup.py has to be configured differently with setup_local.py.  I would be happy to include some documentation when you have the updated patches ready, or even if you decide not to update the patches.

**Comment by pbiering** [comment]
Thank you for confirmation that 4.0.0 has broken "v2 checkbox" (and imho also "v2 invisible"), will file a ticket there.
And yes, I'm working already on new set of patches, potentially ready for preview tomorrow already.

**Comment by pbiering** [comment]
@fspc : I don't understand the request removing from django/contrib/admin/templates/admin/login.html, because if done, the admin portal login is without CAPTCHA protection.
```
  <div class="form-row">
    {{ form.captcha.errors }}
    {{ form.captcha }}
  </div>
```

**Comment by pbiering** [comment]
Sneak preview: https://github.com/pbiering/mailman3-rpm/tree/captcha-rework

Were also able to repair Google's reCAPTCHA v2 "checkbox" and "hidden", looks like upstream broke something during 3.0.0 -> 4.0.0, had to fetch some changes from 4.0.0->4.1.0(upcoming) as well revert some 3.0.0->4.0.0

**Comment by pbiering** [comment]
V3 is not default, but now supported, see here https://github.com/pbiering/mailman3-rpm/releases/tag/3.3.9-26

**Comment by fspc** [comment]
> @fspc : I don't understand the request removing from django/contrib/admin/templates/admin/login.html, because if done, the admin portal login is without CAPTCHA protection.
> 
> ```
>   <div class="form-row">
>     {{ form.captcha.errors }}
>     {{ form.captcha }}
>   </div>
> ```

What happens is that the recaptcha script - https://www.gstatic.com/recaptcha/releases/u-xcq3POCWFlCr3x8_IPxgPu/recaptcha__en.js - inserts a hidden input tag with the correct attributes, so another form element is not required.  When you use V3, by default, a badge is shown in the lower right hand corner, this can be hidden with css, however, in this case you would need to include the branding text - https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed .  The end result is that real visitors to the site never need to interact with recaptcha, while bots have a much different experience.

A visible field with form-row doesn't work for V3 because it reports an error when the form is submitting.
